#Say you want to select the 10 values of COLUMN A after and before a specific value of that column
WITH NUMBERED_TABLE AS
(
SELECT ROW_NUMBER() OVER (ORDER BY ORDER_COLUMN) AS ROW_NUMBER, .*
FROM ORIGINAL_TABLE
)
SELECT * From NUMBERED_TABLE
WHERE ROW_NUMBER BETWEEN
(SELECT ROW_NUMBER FROM NUMBERED_TABLE WHERE A=COLUMN_VALUE) - 10
AND 
(SELECT ROW_NUMBER FROM NUMBERED_TABLE WHERE A=COLUMN_VALUE) + 10
